# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Jaén 2015"
email: "contacto@gdgjaen.xyz"
description: "GDG DevFest es un conjunto de eventos por todo el mundo"
baseurl: ""
url: "http://gdgjaen.xyz"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-68400697-1"
googleAnalyticsSiteUrl: "gdgjaen.xyz"
siteVerification: "xYx4smZJbD6N50Mi222bBDS1MQ2kNBtEaNmAwUYEYKg"

# Organizer Info
organizerName: "GDG Jaén"
organizerAlternateName: "Google Developer Group Jaén"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "contacto@gdgjaen.xyz"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.gdgjaen.xyz"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, jaen"
twitterAccount: "@GDGJaen"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/agenda/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Nosotros"}
 - {permalink: "/logistics/", text: "Planifícate"}
rightNavigationButtons:
 - {link: "/#tickets", text: "Consigue una entrada"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG Jaén DevFest <typeout> 2015"
eventDate: "7 de noviembre, 2015"
typeoutTextValues: '"", "Android", "Functional Programming", "Cloud", "Community"'
typeoutFallback: "Jaén"
heroButtons:
 - {permalink: "/#tickets", text: "Consigue una entrada"}


# About Block
aboutTitle: "Sobre nuestro primer Devfest"
aboutBlock:
 - {title: "Devfest", image: "devfest.png", text: "Los Devfests son el mayor evento organizado anualmente por los Google Developers Groups y... ¡Por primera vez llegan a Jaén!" }
 - {title: "Ponencias", image: "ponencias.jpg", text: "Vendrán a darnos charlas speakers de primerísimo nivel de toda España... ¡Pagados con sacos de cacahuetes de la mejor calidad!" }
 - {title: "Networking", image: "networking.jpg", text: "El Devfest supone una oportunidad única para hacer crecer la comunidad de desarrolladores de Jaén. ¿Te lo vas a perder?" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "", info: "asistentes", detail: "de toda Andalucía"}
 - {count: "15", specialCharacter: "", info: "horas", detail: "de tecnología y comunidad"}
 - {count: "10", specialCharacter: "+", info: "speakers", detail: "de toda España"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Localización"
eventLocationName: "Centro de Convenciones de IFEJA"
eventLocationLink: "http://www.ifeja.org/"
eventStreetAddress: "Prolongación de Carretera de Granada s/n"
eventAddressLocality: "Jaén"
eventAddressLocalityRegion: "Andalucía"
eventPostalCode: "23003"
eventAddressCountry: "España"
eventStartTime: "2015-11-07T09:00"
eventDoorTime: "08:45"
eventEndTime: "2015-11-07T21:00"
eventPlaceCoordinates: "37.776666, -3.757317"
mapCenterCoordinates: "37.777757,-3.7587247"
mapMobileCenterCoordinates: "37.777757,-3.7587247"

# Venue Block
venueBlockTitle: "VENUE"
venueBigImage: "guadalquivir.jpg"
venueSmallImage1: "venue_0.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_2.jpg"
venueTitle: "Palacio de Congresos de IFEJA"
venueFeatures: ["Aparcamiento gratuito", "Restaurante y Cafetería propio","Pantalla 6x4,5m"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "¿Qué se está diciendo?"
twitterHashTag: "devfestjaen"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Patrocinar"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscríbete para recibir novedades en tu correo"
subscribeAction: "//xyz.us12.list-manage.com/subscribe/post?u=3b331410093c6e3fe48ed7a2c&amp;id=91115c2eb5"
subscribeInfo: "Recibirás un correo con las últimas novedades sobre el GDG DevFest Jaén y sobre actividades organizadas por el GDG Jaén."

# Tickets Block
ticketsTitle: "Entradas"
ticketsInfo: ""
ticketsOffers:
 -
  name: "Entrada general"
  price: "5"
  priceCurrency: "€"
  ticketsNumber: "80"
  ribbon: null
  buyButtonLink: "https://www.eventbrite.es/e/entradas-devfest-jaen-2015-19077358894"
  buyButtonText: "Comprar ahora"
  ticketContentList: ["Acreditación como asistente", "Acceso a todas las charlas y actividades", "Networking", "Sorpresas"]
  validFrom: "2015-10-16T00:00"
  validThrough: "2015-11-05T23:59"
  featured: true
  disabled: false

# Footer
socialLinks:
 - {link: "https://plus.google.com/116243063925737679471/posts", icon: "google-plus"}
 - {link: "https://twitter.com/GdgJaen", icon: "twitter"}
 - {link: "https://www.facebook.com/GDGJaen", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contacto@gdgjaen.xyz", text: "contacto@gdgjaen.xyz"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: true
discusShortName: "devfestjaen"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Nosotros"
aboutUs: "El GDG de Jaén está dirigido por ex-estudiantes y estudiantes de la Universidad de Jaén y nació con el objetivo de unir y generar la comunidad que la provincia llevaba tanto tiempo pidiendo. Si bien en esta sección podrás ver quienes estamos detrás de todo esto, cualquiera con interés e inquietudes puede colaborar... ¡Quizás en el proxímo DevFest aparezcas tú! Al fin y al cabo el GDG no son sólo 4 o 5 personas, lo formamos todos los que asistimos a los eventos y aportamos ganas e ideas. Nuestra última finalidad es proporcionarle a las nuevas generaciones de estudiantes lo que a nosotros nos hubiera gustado tener cuando empezamos."

# Logistics Find Way Block
findWayTitle: "Encuentra aquí tu ruta"
findWayDistance: "Distancia"
findWayDriving: "En coche"
findWayWalking: "Andando"
findWayBicycling: "En bici"
findWayTransit: "Transporte público"
#findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "39.6872221,-3.6584213"
logisticsMapMobileCenterCoordinates: "39.6872221,-3.6584213"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Alrededor de IFEJA"
directionDetailsCards:
 - {title: "Llegar en coche", information: 'Quien quiera venir en coche, dispone de aparcamiento gratuito junto a la entrada del centro de convenciones de IFEJA.'}
 - {title: "Transporte público", information: 'La línea 13 de autobuses urbanos de Jaén tiene una parada en IFEJA. La frecuencia es cada hora en torno a las y media. Ver <a href="http://www.aytojaen.es/portal/p_20_contenedor1.jsp?seccion=s_fdes_d1_v1.jsp&contenido=781&tipo=6&nivel=1400&layout=p_20_contenedor1.jsp&codResi=1&language=es&codMenu=133&codMenuPN=2&codMenuSN=96&codMenuTN=131" target="_blank">horarios</a>.'}
 - {title: "Taxi", information: 'Si prefieres utilizar un taxi como forma de moverte, el número para reservar uno en Jaén es el 953 22-22-22 o 953 27-10-10. Podéis solicitar un taxi vía Whatsapp dirigiéndoos a esos mismos números.'}
 - {title: "Para comer", information: 'El edificio dispone de cafetería y habrá un menú especial para la comida de mediodía. Sois libres de traer vuestra propia comida. Además podréis encontrar otras alternativas en el centro de la ciudad o en un centro comercial cercano.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon    
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
